version: '3'
services:
  nats:
    image: nats:1.2.0
    restart: unless-stopped
    ports:
     - "4222:4222"  # for clients
     - "8222:8222"  # for monitoring/reporting
    #  - "6222:6222"  # routing port for clustering
    