/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScastRouteImport } from './routes/scast'
import { Route as TedcheckRouteImport } from './routes/tedcheck'
import { Route as PrototypeMarkRouteImport } from './routes/prototype.mark'
import { Route as PrototypeNetworkRouteImport } from './routes/prototype.network'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScastRoute = ScastRouteImport.update({
  id: '/scast',
  path: '/scast',
  getParentRoute: () => rootRouteImport,
} as any)
const TedcheckRoute = TedcheckRouteImport.update({
  id: '/tedcheck',
  path: '/tedcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMarkRoute = PrototypeMarkRouteImport.update({
  id: '/prototype/mark',
  path: '/prototype/mark',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeNetworkRoute = PrototypeNetworkRouteImport.update({
  id: '/prototype/network',
  path: '/prototype/network',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scast': typeof ScastRoute
  '/tedcheck': typeof TedcheckRoute
  '/prototype/mark': typeof PrototypeMarkRoute
  '/prototype/network': typeof PrototypeNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scast': typeof ScastRoute
  '/tedcheck': typeof TedcheckRoute
  '/prototype/mark': typeof PrototypeMarkRoute
  '/prototype/network': typeof PrototypeNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scast': typeof ScastRoute
  '/tedcheck': typeof TedcheckRoute
  '/prototype/mark': typeof PrototypeMarkRoute
  '/prototype/network': typeof PrototypeNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/scast' | '/tedcheck' | '/prototype/mark' | '/prototype/network'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scast' | '/tedcheck' | '/prototype/mark' | '/prototype/network'
  id:
    | '__root__'
    | '/'
    | '/scast'
    | '/tedcheck'
    | '/prototype/mark'
    | '/prototype/network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScastRoute: typeof ScastRoute
  TedcheckRoute: typeof TedcheckRoute
  PrototypeMarkRoute: typeof PrototypeMarkRoute
  PrototypeNetworkRoute: typeof PrototypeNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scast': {
      id: '/scast'
      path: '/scast'
      fullPath: '/scast'
      preLoaderRoute: typeof ScastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tedcheck': {
      id: '/tedcheck'
      path: '/tedcheck'
      fullPath: '/tedcheck'
      preLoaderRoute: typeof TedcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/mark': {
      id: '/prototype/mark'
      path: '/prototype/mark'
      fullPath: '/prototype/mark'
      preLoaderRoute: typeof PrototypeMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/network': {
      id: '/prototype/network'
      path: '/prototype/network'
      fullPath: '/prototype/network'
      preLoaderRoute: typeof PrototypeNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScastRoute: ScastRoute,
  TedcheckRoute: TedcheckRoute,
  PrototypeMarkRoute: PrototypeMarkRoute,
  PrototypeNetworkRoute: PrototypeNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
