/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ScastRouteImport } from './routes/scast'
import { Route as Ted1kRouteImport } from './routes/ted1k'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ScastRoute = ScastRouteImport.update({
  id: '/scast',
  path: '/scast',
  getParentRoute: () => rootRouteImport,
} as any)
const Ted1kRoute = Ted1kRouteImport.update({
  id: '/ted1k',
  path: '/ted1k',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/scast': typeof ScastRoute
  '/ted1k': typeof Ted1kRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/scast': typeof ScastRoute
  '/ted1k': typeof Ted1kRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/scast': typeof ScastRoute
  '/ted1k': typeof Ted1kRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network' | '/scast' | '/ted1k'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network' | '/scast' | '/ted1k'
  id: '__root__' | '/' | '/network' | '/scast' | '/ted1k'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRoute: typeof NetworkRoute
  ScastRoute: typeof ScastRoute
  Ted1kRoute: typeof Ted1kRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scast': {
      id: '/scast'
      path: '/scast'
      fullPath: '/scast'
      preLoaderRoute: typeof ScastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ted1k': {
      id: '/ted1k'
      path: '/ted1k'
      fullPath: '/ted1k'
      preLoaderRoute: typeof Ted1kRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRoute: NetworkRoute,
  ScastRoute: ScastRoute,
  Ted1kRoute: Ted1kRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
