version: "3"

services:
  ddclient:
    image: linuxserver/ddclient
    restart: unless-stopped
    volumes:
      - ./config/ddclient:/config

  caddy:
    # image: caddy:2
    # this is our own caddy image with dns challenge support for our providers
    # image: ghcr.io/daneroo/caddy:2-dns
    build:
      context: .
      dockerfile: Dockerfile-caddy
    restart: unless-stopped
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/dotaws-im-dan:/root/.aws
    ports:
      - "80:80" # local only
      - "443:443" # port-forwarded from wifi-router

  nats:
    # image: nats:1.2.0
    # Replaced this with synadia nightly to get websockets, pinned to known working version
    # image: nats:2.7.2
    image: synadia/nats-server:nightly-20220224 # This is v2.7.3-beta.3
    restart: unless-stopped
    volumes:
      - ./config/nats/nats-server.conf:/nats/conf/nats-server.conf
    ports:
      - "4222:4222" # for clients - port forwarded from router
      - "6222:6222" # routing port for clustering
      - "8222:8222" # for monitoring/reporting
      - "9222:9222" # for websockets

  # TODO: rename to natsql
  natsql:
    # build will replaced by image when pushed to registry
    build: ../packages/natsql/
    # image: qcic-api:vx.y.z
    restart: unless-stopped
    environment:
      # no value inherits from host (but not docker-machine host...)
      # HOSTNAME should not be overwritten - use HOSTALIAS instead
      HOSTALIAS: "natsql.dl.imetrical.com"
      NATSURL: "nats://nats.dl.imetrical.com:4222"
    ports:
      - "5000:5000" # for http & ws

  status:
    # This entire source should disappear with live services (hasura/ipfs)
    # build will replaced by image when pushed to registry
    build: ../packages/status/
    # image: qcic-status:vx.y.z
    restart: unless-stopped
    # ports:
    #  - "8000:8000"  # forweb
    volumes:
      - ../packages/status/dist:/usr/src/app/dist
      - "${HOME}/Library/Application Support/com.vercel.cli/:/root/.now"
      - ../packages/status/credentials.loggly.json:/usr/src/app/credentials.loggly.json
      - ../packages/status/credentials.mysql.json:/usr/src/app/credentials.mysql.json
      - ../packages/status/credentials.postgres.json:/usr/src/app/credentials.postgres.json
