# Pinning this builder only to major number, hoping Caddy take semver seriously!
# See tags and dpcs: https://hub.docker.com/_/caddy
FROM caddy:2-builder AS builder

# These are the go module versions.
# they should be updated.
RUN xcaddy build \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/caddy-dns/googleclouddns@v1.0.2 \
  --with github.com/caddy-dns/route53@v1.1.2

# Also pinned to the major number only (and matches the -builder variant)
FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

# TODO, I could also copy in my configuraion...
#  ./config/caddy/Caddyfile:/etc/caddy/Caddyfile