version: "3"

services:
  ddclient:
    image: linuxserver/ddclient
    restart: unless-stopped
    volumes:
      - ./config/ddclient:/config

  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
    ports:
      - "80:80" # local only
      - "443:443" # port-forwarded from wifi-router

  nats:
    # image: nats:1.2.0
    # Replaced this with nightly to get websockets, pin to version as soon as websokckets are GA
    image: synadia/nats-server:nightly
    restart: unless-stopped
    volumes: 
      -  ./config/nats/nats-server.conf:/nats/conf/nats-server.conf
    ports:
      - "4222:4222" # for clients - port forwarded from router
      - "6222:6222" # routing port for clustering
      - "8222:8222" # for monitoring/reporting
      - "9222:9222" # for websockets

  # rename to natsql
  api:
    # build will replaced by image when pushed to registry
    build: ../packages/api/
    # image: qcic-api:vx.y.z
    restart: unless-stopped
    environment:
      # no value inherits from host (but not docker-machine host...)
      - HOSTNAME
    ports:
      - "5000:5000" # for http & ws

  status:
    # This entire source should disappear with live services (hasura/ipfs)
    # build will replaced by image when pushed to registry
    build: ../packages/status/
    # image: qcic-status:vx.y.z
    restart: unless-stopped
    # ports:
    #  - "8000:8000"  # forweb
    volumes:
      - ../packages/status/dist:/usr/src/app/dist
      - "${HOME}/Library/Application Support/com.vercel.cli/:/root/.now"
      - ../packages/status/credentials.loggly.json:/usr/src/app/credentials.loggly.json
      - ../packages/status/credentials.mysql.json:/usr/src/app/credentials.mysql.json
      - ../packages/status/credentials.postgres.json:/usr/src/app/credentials.postgres.json
