# List available commands
default:
    just -l

alias run := start
# Status (docker compose)
start:
    mix run_qcic

# Run and format the output as Markdown
markdown:
    @# GUM_FORMAT_THEME:  pink (default), light, notty, dracula; I set it in my bashrc
    mix run_qcic | gum format # default theme set in bashrc

# Mix Tests
test:
    mix test

# Credo Linter
lint:
    mix credo --strict    